### ISSUE TITLE
Re-apply veinjs

### ISSUE THREAD

**Issue by mjau-mjau** [israelidanny/veinjs#25]
In the project I am working on, I have the need to remove the stylesheet created by veinjs. Removal of vein is simple:
```
$('style#vein').remove();
```
The problem is, veinjs does not work any more if the initially applied vein stylesheet is removed. You would think it recreates the style, but it seems to think it still exists so nothing happens. You might wonder why I need to do this, but in short it is because CSS stylesheets loaded dynamically *after* veinjs is applied, overwrite veinjs styles in Explorer. It doesn't work to just delete all styles in vein and re-apply them. Thanks!

**Comment by mjau-mjau** [comment]
I managed to fix it by commenting out the following condition starting on line 77 of veinjs:
```// if(!self.element) {```
Shouldn't the condition above also perhaps check if the #vein stylesheet actually exists, and if not, create it? As mentioned, I need to remove and re-apply the vein stylesheet programmatically after remote stylesheets are loaded, because various browsers have different ways of determining style priority. This is for a nice page style/theme/font selector btw ...

**Comment by israelidanny** [comment]
Interesting... Let's think for a moment. Don't we ALWAYS want veinjs to be
the last ruling stylesheet?
What about a method to ensure that?

I do think that this is something that could be taken care of by a check
for the existence of a stylesheet. Do you wanna fix and submit a PR? I'll
try to do it as well if I get enough time.

**Comment by mjau-mjau** [comment]
> Don't we ALWAYS want veinjs to be the last ruling stylesheet?
> What about a method to ensure that?

The problem is, while chrome/FF/Safari give priority to the *last listed* stylesheet in the head, IE will give priority to the *last loaded* stylesheet regardless of where in the head it is, which might make it tedious to add a method to ensure vein priority. Let me see if I can submit a PR tomorrow to check if #vein exists.
