### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by jondashkyle** [israelidanny/veinjs#27]
Thoughts about adding this to the NPM registry?

**Comment by ArthurClemens** [comment]
+1

**Comment by Leeds-eBooks** [comment]
Until then: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by Leeds-eBooks** [comment]
Ah, I spoke too soon, this still requires a `package.json`. I think I'll fork this project and put one in.

**Comment by Leeds-eBooks** [comment]
Ok if anyone wants to use npm to handle this package, you can run the following until it veinjs gets added to npm as a package:

```sh
npm install git+https://github.com/Leeds-eBooks/veinjs.git\#npm-leeds-ebooks
```
